# Site settings
url: https://www.sheffieldviking.org.uk
title: Sheffield Viking Sailing Club
email: info@sheffieldviking.org.uk
author: SVSC
description: > # "Dinghy sailing and racing in NW Sheffield"

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from
